[meta]
name = "ASR" 
pretrained_path = "nguyenvulebinh/wav2vec2-base-vietnamese-250h"
seed = 42
epochs = 20
save_dir = "saved/" 
gradient_accumulation_steps = 2
use_amp = false
device_ids = "0"
sr = 16000
max_clip_grad_norm = 5.0

[special_tokens]
bos_token = "<bos>"
eos_token = "<eos>"
unk_token = "<unk>"
pad_token = "<pad>"


# Not available yet
[huggingface]
push_to_hub = false
push_every_validation_step = false
overwrite_output_dir = false
blocking = false
    [huggingface.args]
    local_dir = "huggingface-hub"
    use_auth_token = true
    clone_from = ""


[train_dataset]
path = "base.base_dataset.BaseDataset"
    [train_dataset.args]
    path = "/dataset/train.txt"
    preload_data = false
    delimiter = "|"
    nb_workers = 16
    
    [train_dataset.dataloader]
    batch_size = 8
    num_workers = 4
    pin_memory = true 
    drop_last = true

    [train_dataset.sampler]
    shuffle = true 
    drop_last = true

    
[val_dataset]
path = "base.base_dataset.BaseDataset"
    [val_dataset.args]
    path = "/dataset/dev.txt"
    preload_data = false
    delimiter = "|"
    nb_workers = 16

    [val_dataset.dataloader]
    batch_size =  1
    num_workers = 4

    [val_dataset.sampler]
    shuffle = false 
    drop_last = false

 
[optimizer]
lr = 8e-6


[scheduler] 
max_lr = 1e-5
    

[trainer]
path = "trainer.trainer.Trainer"
    [trainer.args]
    validation_interval = 500
    save_max_metric_score = false 
